// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
  repositories {
    google()
    mavenCentral()
  }
  dependencies {
    classpath("com.android.tools.build:gradle:8.7.3")
    classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:2.1.20")
  }
}

ext {
  buildToolsVersion = "35.0.0"
  minSdkVersion = 24
  compileSdkVersion = 35
  targetSdkVersion = 35
  ndkVersion = "23.1.7779620"
  kotlinVersion = "2.1.20"
}

allprojects {
  ext.react = [
      enableHermes: true,
      cliPath: new File(["node", "--print", "require.resolve('react-native/cli.js')"].execute(null, rootDir).text.trim()).absolutePath,
  ]
  repositories {
    google()
    mavenCentral()
    maven { url "https://www.jitpack.io" }
    maven {
      url new File(["node", "--print", "require('path').dirname(require.resolve('react-native/package.json'))"].execute(null, rootDir).text.trim(), "android")
    }
    maven {
      url new File(["node", "--print", "require('path').dirname(require.resolve('jsc-android/package.json'))"].execute(null, rootDir).text.trim(), "dist")
    }
  }
}

subprojects { project ->
  def manifestFile = file("${project.projectDir}/src/main/AndroidManifest.xml")
  def pkg = null
  if (manifestFile.exists()) {
    def manifestContent = manifestFile.text
    def matcher = manifestContent =~ /package="([^"]+)"/
    if (matcher.find()) {
        pkg = matcher.group(1)
    }
  }

  project.plugins.withId("com.android.library") {
    project.android {
      if (pkg != null) {
        namespace = pkg
      } else if (namespace == null) {
        if (project.name == "react-native-gesture-handler") {
          namespace = "com.swmansion.gesturehandler.react"
        } else {
          namespace = "com.anonymous." + project.name.replaceAll("[^a-zA-Z0-9_]", "")
        }
      }
      buildFeatures {
        buildConfig true
      }
    }
  }

  project.afterEvaluate {
    project.tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
      kotlinOptions {
        jvmTarget = "1.8"
      }
    }
  }
}

