rootProject.name = 'O2O'
apply from: new File(["node", "--print", "require('path').join(require.resolve('react-native/package.json'), '../../@react-native-community/cli-platform-android/native_modules.gradle')"].execute(null, rootDir).text.trim()); applyNativeModulesSettingsGradle(settings)
include ':app'
