rootProject.name = 'O2O'
apply from: new File(["node", "--print", "require('path').dirname(require.resolve('@react-native-community/cli-platform-android/package.json', { paths: [require.resolve('react-native/package.json')] })) + '/native_modules.gradle'"].execute(null, rootDir).text.trim()); applyNativeModulesSettingsGradle(settings)
include ':app'
